#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.178:3306/bigstore?serverTimezone=GMT%2B8&amp&useSSL=false
    username: root
    password: root
#mybatis mapper位置设置
mybatis:
  mapper-locations: classpath:mapper/*.xml